# Generated by Django 5.0.7 on 2024-10-31 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
